name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable
      - run: cargo check --manifest-path mrmouth/Cargo.toml
      - run: cargo test --manifest-path mrmouth/Cargo.toml
      - run: cargo clippy --manifest-path mrmouth/Cargo.toml -- -D warnings
